services:
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/
    depends_on:
      - mysql
    networks:
      - bitrix

  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    restart: on-failure
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    networks:
      - bitrix

  mysql:
    image: mysql:8.0
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=only
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_bitrix:/var/lib/mysql
    networks:
      - bitrix

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - bitrix

volumes:
  db_bitrix:


networks:
  bitrix:
